### ISSUE TITLE
Adding reservation not working

### ISSUE THREAD

**Issue by anewman24** [nhngoc02/KennelProject_SWE#108]
Get the error below, which typically indicates the schema is not correctly formatted. I would recommend checking the reservation.js file in the db_modules folder, and console.log the attempted edit to see how it differs.

Another Issue: 

Unable to add reservation: MongoServerError: Document failed validation
    at InsertOneOperation.execute 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeOperationAsync (KennelProject_SWE\kennel_link\node_modules\mongoose\node_modules\mongodb\lib\operations\execute_operation.js:106:16) {
  index: 0,
  code: 121,
  errInfo: {
    failingDocumentId: new ObjectId('66292cfe74d55fd0c774eed1'),
    details: { operatorName: '$jsonSchema', schemaRulesNotSatisfied: [Array] }
  },
  [Symbol(errorLabels)]: Set(0) {}
}

**Comment by anewman24** [comment]
Currently I believe the error is found in the findPetID function in the reservationModel.js. Some more debugging is required to actually fixed the issue. Below is the error I got when trying to debug.

Unable to add reservation: TypeError: Cannot read properties of null (reading 'petID')
    at findPetID (KennelProject_SWE\kennel_link\scripts\reservationModel.js:76:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.addReservationWithCheck (KennelProject_SWE\kennel_link\scripts\reservationModel.js:95:26)
    at async KennelProject_SWE\kennel_link\app.js:153:20
